### PR TITLE
fix(ConcertoForm): fix various bugs including DateTime error

### LINKED ISSUE #131: DateTime Objects cause ui-concerto to crash
# Bug Report 🐛

When using a modelfile which contains a `DateTime` Attribute, the form crashes either when modifying the sample value or instantly. 
## Expected Behavior

I expect the form generator to generate the form correctly and either generate a sample value or not, depending on the options. Furthermore it should not crash when wrong values are inserted, as this can happen while typing.
## Current Behavior

The form generator crashes with Error 130:
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=
Sometimes only the error message "Invalid JSON instance provided" is displayed.
## Possible Solution

Maybe something to do with input checking? 
## Steps to Reproduce

1. visit https://ap-web-components.netlify.app/?path=/story/concerto-form--demo
2. under  Knobs > Model change an attribute of `concept Address`to `DateTime`
3. If Form renders, try to change the value displayed in it.
4. observe error message

## Context (Environment)

I am using web-components to implement contracts via a web application on HLF. This issue prevents me from updating from `concerto-ui-core: 0.82.8`. 
### Desktop
 - OS: Arch linux, Windows
 - Browser: Firefox, Chromium
 - Version: 78, 83.0

## Detailed Description

In my eyes, `ui-concerto` should be able to render every primitive type and allow users to change their values, even if they temporarily are in an invalid format, like a DateTime String missing some character because the user is still typing. An indication of the value being incorrect is okay, as long as the user is not prevented from completing the value, by  i.e. replacing the wrong value with something else.

### PR DESCRIPTION
**Pull request by DianaLease**
Signed-off-by: Diana Lease <dianarlease@gmail.com>

# Closes #131 

### Changes

- Fixes DateTime error that caused crash. The value supplied by the form on change is already an ISO string, so we shouldn't use `toISOString` on it, unless there is no value (ie. we just changed the model to be DateTime), then use `new Date().toISOString()` to get the current date/time. Slice on the string was changed from `(0,19)` to `(0,16)` to exclude seconds.
- Fixes issue where empty strings were not allowed as values because `e.value` on an empty string is falsey and `e.target.value` would throw an error in the console.
- Adds keys to iterable React components where necessary
- Removed `types` from onModelChange storybook action because it throws an error in the console and does not log as a storybook action.

### Flags
- I'll make this same PR into master after this one goes in, but I wanted to be able to get this bug fix into the v0.93 branch to be available to use now.

### CODE REVIEW

File: packages/ui-concerto/src/lib/components/fields.js [hunk 1]
```diff
@@ -75,18 +75,21 @@ export const ConcertoDateTime = ({
...
+}) => {
+  const date = Date.parse(value) ? value : new Date().toISOString();
+  return (
   <Form.Field required={required}>
     <ConcertoLabel skip={skipLabel} name={field.getName()} />
     <Input
       type={type}
       readOnly={readOnly}
-      value={new Date(value).toISOString().slice(0, 19)}
+      value={date.slice(0, 16)}
```
Comment (jeromesimeon) [inline packages/ui-concerto/src/lib/components/fields.js:86]: I don't fully understand this PR... and most of it looks fine, but this `slice`call looks quite arbitrary. Can you explain what the purpose / reasoning behind it is?

Comment (DianaLease) [reply packages/ui-concerto/src/lib/components/fields.js:86]: This is just for the form itself, which only allows the user to choose a date. The value supplied by the form on change is already an ISO string.
