### PR TITLE
fix(ui-markdown-editor): handle cut image operation - #294

### LINKED ISSUE #294: Unable to Cut an image
# Bug Report 🐛
If we click an image in the markdown-editor and press `ctrl+x` the image should disapper. Here the image should not be `selected` just `clicked` and then press `ctrl + x.` THe image just stays i.e. shows the behaviour of copy rather than cut.
## Expected Behavior
The image should be deleted.
## Current Behavior
THe image is not deleted.

fd59c203-1703-4029-94d8-6cb87ca15238

## Steps to Reproduce
1. Click on the image 
2. Press `Ctrl + X`
3. Image should disapper

## Context (Environment)
 - OS: Ubuntu 20.04
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Cronus1007**
# Closes #294 
The Cut operation that can't be performed upon the images is regulated.
### Steps to see the Change
- Click an image
- Press Ctrl+X
- Image disapperas 
- Normal cut functionality

### Related Issues
- Issue #294 
- Pull Request #<NUMBER>

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

### CODE REVIEW

File: packages/ui-markdown-editor/src/index.js [hunk 1]
```diff
@@ -130,10 +129,15 @@ export const MarkdownEditor = (props) => {
     const CICERO_MARK_DOM = slateTransformer.toCiceroMark(SLATE_DOM);
     const HTML_DOM = htmlTransformer.toHtml(CICERO_MARK_DOM);
     const MARKDOWN_TEXT = ciceroMarkTransformer.toMarkdown(CICERO_MARK_DOM);
+    const [imageNode] = Editor.nodes(editor, { match: n => n.type === 'image' });
```
Comment (mttrbrts) [inline packages/ui-markdown-editor/src/index.js:132]: @irmerk @DianaLease @dselman Is this the best way to detect if the operation applies to an 'image'?

**Review by mttrbrts — COMMENTED** [review]
Good spot @Cronus1007. I'm happy with the change, but will need a review from one of the maintainers with deeper knowledge of Slate to confirm.

File: packages/ui-markdown-editor/src/index.js (hunk 1 above)
Comment (Cronus1007) [reply packages/ui-markdown-editor/src/index.js:132]: @irmerk @DianaLease @dselman Also tell me the best way to detect if the operation applies to  'text'

Comment (irmerk) [reply packages/ui-markdown-editor/src/index.js:132]: We have precedent here for detecting an image, see [L175](https://github.com/accordproject/web-components/pull/298/files#diff-46ada2eb1165549f5e15ed60cb7838af16bb6ab14c15530502dde1c2590c2e2cR175) under `handleDrop` in this file. 

I'd look for other inspiration on a text node.

**Review by irmerk — CHANGES_REQUESTED** [review]
This looks good to me. Can you rebase to get rid of 1c6ee38?

**Comment by Cronus1007** [comment]
@irmerk I

File: packages/ui-markdown-editor/src/index.js (hunk 1 above)
Comment (Cronus1007) [reply packages/ui-markdown-editor/src/index.js:131]: @irmerk Sure.

File: packages/ui-markdown-editor/src/index.js [hunk 2]
```diff
@@ -129,10 +128,15 @@ export const MarkdownEditor = (props) => {
...
 
     event.clipboardData.setData('text/html', HTML_DOM);
     event.clipboardData.setData('text/plain', MARKDOWN_TEXT);
 
+    if (cut && imageNode) {
```
Comment (raghavdhingra-bst) [inline packages/ui-markdown-editor/src/index.js:136]: @Cronus1007 LGTM

Comment (raghavdhingra) [inline packages/ui-markdown-editor/src/index.js:136]: @Cronus1007 LGTM

**Review by irmerk — APPROVED** [review]
